### ISSUE TITLE
How can I use it in an Activity

### ISSUE THREAD

**Issue by woxingxiao** [lopspower/Biometric#1]
Thanks for your excellent work for this lib. 👍👍

But why the `BiometricHelper` has to be instanced in a fragment?  How can I use it in an activity?
```kotlin
class BiometricHelper(private val fragment: Fragment) 
```
Isn't this a better way?
```kotlin
class BiometricHelper(private val context: Context) 
```

**Comment by lopspower** [comment]
Hello,
Sorry this is not possible due to the implementation of Google of **BiometricPrompt**.
You absolutely need a Fragment or a FragmentActivity:
https://developer.android.com/reference/androidx/biometric/BiometricPrompt#BiometricPrompt(androidx.fragment.app.FragmentActivity,%20java.util.concurrent.Executor,%20androidx.biometric.BiometricPrompt.AuthenticationCallback)

**Comment by rranjithkumar100** [comment]
FragmentActivity also unable to use. It's only accepts fragment. no use
